#!/usr/bin/env python3
"""
Phase 4 Analytics Dashboard - JSON Edition
==========================================

Reads pre-calculated results from JSON files instead of querying database.
Fast, secure, scalable visualization layer.

JSON files are generated by extraction scripts and synced to HF Space.
"""

import os
import json
from datetime import datetime
import streamlit as st
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from streamlit_option_menu import option_menu

# ============================================================================
# CONFIG
# ============================================================================

# Try multiple paths for JSON files (local, HF, etc)
JSON_PATHS = [
    '/opt/ai-optimizer/results',
    '/app/results',  # HF deployment
    './results',
    '../results'
]

st.set_page_config(
    page_title="Phase 4: Аналитика кампаний",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ============================================================================
# JSON LOADERS
# ============================================================================

def find_json_file(filename):
    """Find JSON file in multiple locations."""
    for path in JSON_PATHS:
        filepath = os.path.join(path, filename)
        if os.path.exists(filepath):
            return filepath
    return None

@st.cache_data(ttl=300)
def load_account_kpi():
    """Load account KPI data from JSON."""
    filepath = find_json_file('account_kpi.json')
    
    if not filepath:
        st.error("❌ account_kpi.json not found in any expected location")
        st.stop()
    
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        # Convert to DataFrame for compatibility
        df = pd.DataFrame(data['data'])
        df['date'] = pd.to_datetime(df['date'])
        
        # Store account CPA in session
        st.session_state['account_cpa'] = data['account_cpa']
        
        return df
    except Exception as e:
        st.error(f"❌ Error loading account_kpi.json: {str(e)}")
        st.stop()

@st.cache_data(ttl=300)
def load_insights():
    """Load insights (good/bad trends) from JSON."""
    filepath = find_json_file('insights.json')
    
    if not filepath:
        st.error("❌ insights.json not found")
        st.stop()
    
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        # Combine good and bad trends
        all_trends = []
        
        for trend in data.get('good_trends', []):
            trend['classification'] = 'good'
            all_trends.append(trend)
        
        for trend in data.get('bad_trends', []):
            trend['classification'] = 'bad'
            all_trends.append(trend)
        
        df = pd.DataFrame(all_trends)
        return df
    except Exception as e:
        st.error(f"❌ Error loading insights.json: {str(e)}")
        st.stop()

# ============================================================================
# PAGE: OVERVIEW
# ============================================================================

def page_overview():
    """Display account KPI overview."""
    st.header("📊 Overview - Account KPI")
    
    # Load data
    kpi_df = load_account_kpi()
    account_cpa = st.session_state.get('account_cpa', 0)
    
    # Summary metrics
    col1, col2, col3, col4 = st.columns(4)
    
    with col1:
        st.metric(
            "Total Cost",
            f"₽{kpi_df['cost'].sum():,.0f}",
            delta=None
        )
    
    with col2:
        st.metric(
            "Total Conversions",
            f"{kpi_df['conversions'].sum():,.0f}",
            delta=None
        )
    
    with col3:
        st.metric(
            "Average CPA",
            f"₽{account_cpa:,.0f}",
            delta=None
        )
    
    with col4:
        days_count = len(kpi_df)
        st.metric(
            "Period",
            f"{days_count} days",
            delta=None
        )
    
    st.divider()
    
    # Cost chart
    st.subheader("💰 Daily Cost")
    fig_cost = px.line(
        kpi_df,
        x='date',
        y='cost',
        markers=True,
        title='Daily Spending',
        labels={'date': 'Date', 'cost': 'Cost (₽)'}
    )
    fig_cost.update_traces(line=dict(color='#FF6B6B', width=3))
    st.plotly_chart(fig_cost, use_container_width=True)
    
    # Conversions chart
    st.subheader("🎯 Daily Conversions")
    fig_conv = px.bar(
        kpi_df,
        x='date',
        y='conversions',
        title='Daily Conversions',
        labels={'date': 'Date', 'conversions': 'Conversions'},
        color_discrete_sequence=['#4ECDC4']
    )
    st.plotly_chart(fig_conv, use_container_width=True)
    
    # Data table
    st.subheader("📋 Daily Details")
    st.dataframe(kpi_df, use_container_width=True)

# ============================================================================
# PAGE: INSIGHTS
# ============================================================================

def page_insights():
    """Display account trends insights."""
    st.header("📈 Insights - Segment Trends (30 days)")
    
    # Load data
    insights_df = load_insights()
    
    # Split by classification
    good_df = insights_df[insights_df['classification'] == 'good']
    bad_df = insights_df[insights_df['classification'] == 'bad']
    
    # Summary
    col1, col2, col3 = st.columns(3)
    
    with col1:
        st.metric("✅ Good Trends", len(good_df))
    
    with col2:
        st.metric("❌ Bad Trends", len(bad_df))
    
    with col3:
        st.metric("Total Segments", len(insights_df))
    
    st.divider()
    
    # Good trends table
    st.subheader("✅ Good Trends (CPA ≤ 67% of avg)")
    
    if not good_df.empty:
        display_good = good_df[[
            'segment_type', 'segment_value', 'cost', 'conversions', 'cpa', 'ratio'
        ]].copy()
        display_good = display_good.sort_values('cost', ascending=False)
        
        st.dataframe(
            display_good,
            column_config={
                'segment_type': st.column_config.TextColumn("Segment"),
                'segment_value': st.column_config.TextColumn("Value"),
                'cost': st.column_config.NumberColumn("Cost (₽)", format="%.0f"),
                'conversions': st.column_config.NumberColumn("Conversions", format="%d"),
                'cpa': st.column_config.NumberColumn("CPA (₽)", format="%.2f"),
                'ratio': st.column_config.NumberColumn("Ratio", format="%.2f")
            },
            use_container_width=True
        )
    else:
        st.info("No good trends found")
    
    st.divider()
    
    # Bad trends table
    st.subheader("❌ Bad Trends (CPA ≥ 150% of avg)")
    
    if not bad_df.empty:
        display_bad = bad_df[[
            'segment_type', 'segment_value', 'cost', 'conversions', 'cpa', 'ratio'
        ]].copy()
        display_bad = display_bad.sort_values('ratio', ascending=False)
        
        st.dataframe(
            display_bad,
            column_config={
                'segment_type': st.column_config.TextColumn("Segment"),
                'segment_value': st.column_config.TextColumn("Value"),
                'cost': st.column_config.NumberColumn("Cost (₽)", format="%.0f"),
                'conversions': st.column_config.NumberColumn("Conversions", format="%d"),
                'cpa': st.column_config.NumberColumn("CPA (₽)", format="%.2f"),
                'ratio': st.column_config.NumberColumn("Ratio", format="%.2f")
            },
            use_container_width=True
        )
    else:
        st.info("No bad trends found")

# ============================================================================
# PAGE: CAMPAIGNS
# ============================================================================

def page_campaigns():
    """Display campaign-level analysis."""
    st.header("🎯 Campaigns - Per-Campaign Analysis")
    
    st.info("Campaign-level analysis coming soon (Level 3 expansion)")

# ============================================================================
# MAIN
# ============================================================================

def main():
    """Main dashboard."""
    
    # Sidebar menu
    with st.sidebar:
        page = option_menu(
            "Navigation",
            ["Overview", "Insights", "Campaigns"],
            icons=["graph-up", "bar-chart", "bullseye"],
            menu_icon="cast",
            default_index=0,
            styles={
                "container": {"padding": "0!important", "background-color": "#fafafa"},
                "icon": {"color": "#FF6B6B", "font-size": "25px"},
                "nav-link": {"font-size": "16px", "margin": "0px", "--hover-color": "#eee"},
            }
        )
        
        st.divider()
        
        st.info("""
        **ℹ️ Data Source**
        
        Results are pre-calculated and read from JSON files.
        
        Updates:
        • Daily (automatic via cron)
        • Last: Check file timestamps
        """)
    
    # Render page
    if page == "Overview":
        page_overview()
    elif page == "Insights":
        page_insights()
    elif page == "Campaigns":
        page_campaigns()

if __name__ == "__main__":
    main()
